In [9]:
import os
import sys
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Project root
PROJECT_ROOT = Path().resolve().parent

sys.path.append(str(PROJECT_ROOT))

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Project Root:", PROJECT_ROOT)

Project Root: D:\travel-intelligence-mlops

Step 1: Check the Users Dataset

In [10]:
print("=" * 60)
print("Gender Distribution")
print("=" * 60)

print(users["gender"].value_counts(dropna=False))


print("\n")

print("=" * 60)
print("Company Distribution (Top 10)")
print("=" * 60)

print(users["company"].value_counts().head(10))


print("\n")

print("=" * 60)
print("Age Statistics")
print("=" * 60)

print(users["age"].describe())

============================================================
Gender Distribution
============================================================
gender
male      452
female    448
none      440
Name: count, dtype: int64


============================================================
Company Distribution (Top 10)
============================================================
company
4You             453
Acme Factory     261
Wonka Company    237
Monsters CYA     195
Umbrella LTDA    194
Name: count, dtype: int64


============================================================
Age Statistics
============================================================
count    1340.000000
mean       42.742537
std        12.869779
min        21.000000
25%        32.000000
50%        42.000000
75%        54.000000
max        65.000000
Name: age, dtype: float64

Step 2: Check the Flights Dataset

In [11]:
print("=" * 60)
print("Flight Type")
print("=" * 60)

print(flights["flightType"].value_counts())


print("\n")

print("=" * 60)
print("Agency")
print("=" * 60)

print(flights["agency"].value_counts())


print("\n")

print("=" * 60)
print("Price Statistics")
print("=" * 60)

print(flights["price"].describe())


print("\n")

print("=" * 60)
print("Distance Statistics")
print("=" * 60)

print(flights["distance"].describe())


print("\n")

print("=" * 60)
print("Time Statistics")
print("=" * 60)

print(flights["time"].describe())

============================================================
Flight Type
============================================================
flightType
firstClass    116418
premium        78004
economic       77466
Name: count, dtype: int64


============================================================
Agency
============================================================
agency
Rainbow        116752
CloudFy        116378
FlyingDrops     38758
Name: count, dtype: int64


============================================================
Price Statistics
============================================================
count    271888.00000
mean        957.37503
std         362.31189
min         301.51000
25%         672.66000
50%         904.00000
75%        1222.24000
max        1754.17000
Name: price, dtype: float64


============================================================
Distance Statistics
============================================================
count    271888.000000
mean        546.955535
std         208.851288
min         168.220000
25%         401.660000
50%         562.140000
75%         676.530000
max         937.770000
Name: distance, dtype: float64


============================================================
Time Statistics
============================================================
count    271888.000000
mean          1.421147
std           0.542541
min           0.440000
25%           1.040000
50%           1.460000
75%           1.760000
max           2.440000
Name: time, dtype: float64

Step 3: Check the Hotels Dataset

In [12]:
print("=" * 60)
print("Top Places")
print("=" * 60)

print(hotels["place"].value_counts().head(20))


print("\n")

print("=" * 60)
print("Days Statistics")
print("=" * 60)

print(hotels["days"].describe())


print("\n")

print("=" * 60)
print("Hotel Price Statistics")
print("=" * 60)

print(hotels["price"].describe())


print("\n")

print("=" * 60)
print("Total Cost Statistics")
print("=" * 60)

print(hotels["total"].describe())

============================================================
Top Places
============================================================
place
Salvador (BH)          5094
Rio de Janeiro (RJ)    5029
Natal (RN)             4829
Sao Paulo (SP)         4828
Recife (PE)            4467
Brasilia (DF)          4437
Campo Grande (MS)      4333
Aracaju (SE)           4205
Florianopolis (SC)     3330
Name: count, dtype: int64


============================================================
Days Statistics
============================================================
count    40552.000000
mean         2.499679
std          1.119326
min          1.000000
25%          1.000000
50%          2.000000
75%          4.000000
max          4.000000
Name: days, dtype: float64


============================================================
Hotel Price Statistics
============================================================
count    40552.000000
mean       214.439554
std         76.742305
min         60.390000
25%        165.990000
50%        242.880000
75%        263.410000
max        313.020000
Name: price, dtype: float64


============================================================
Total Cost Statistics
============================================================
count    40552.000000
mean       536.229513
std        319.331482
min         60.390000
25%        247.620000
50%        495.240000
75%        742.860000
max       1252.080000
Name: total, dtype: float64

📌 Step 4: Duplicate Check

In [13]:
print("Users duplicate rows:", users.duplicated().sum())
print("Flights duplicate rows:", flights.duplicated().sum())
print("Hotels duplicate rows:", hotels.duplicated().sum())


print()

print("Duplicate User Codes:", users["code"].duplicated().sum())
print("Duplicate Flight Travel Codes:", flights["travelCode"].duplicated().sum())
print("Duplicate Hotel Travel Codes:", hotels["travelCode"].duplicated().sum())

Users duplicate rows: 0
Flights duplicate rows: 0
Hotels duplicate rows: 0

Duplicate User Codes: 0
Duplicate Flight Travel Codes: 135944
Duplicate Hotel Travel Codes: 0

📌 Step 5: Date Inspection

In [14]:
print(flights["date"].head(10))

print()

print(hotels["date"].head(10))

0    09/26/2019
1    09/30/2019
2    10/03/2019
3    10/04/2019
4    10/10/2019
5    10/12/2019
6    10/17/2019
7    10/20/2019
8    10/24/2019
9    10/26/2019
Name: date, dtype: object

0    09/26/2019
1    10/10/2019
2    11/14/2019
3    12/12/2019
4    12/26/2019
5    01/09/2020
6    02/27/2020
7    04/16/2020
8    05/07/2020
9    05/14/2020
Name: date, dtype: object

In [15]:
print("=" * 60)
print("Users")
print("=" * 60)

print("Gender")
print(users["gender"].unique())

print("\n")

print("Companies")
print(users["company"].nunique())


print("\n\n")

print("=" * 60)
print("Flights")
print("=" * 60)

print("Flight Types")
print(flights["flightType"].unique())

print("\n")

print("Agencies")
print(flights["agency"].unique())


print("\n\n")

print("=" * 60)
print("Hotels")
print("=" * 60)

print("Places")
print(hotels["place"].nunique())
print(hotels["place"].head(20))

============================================================
Users
============================================================
Gender
['male' 'female' 'none']


Companies
5



============================================================
Flights
============================================================
Flight Types
['firstClass' 'economic' 'premium']


Agencies
['FlyingDrops' 'CloudFy' 'Rainbow']



============================================================
Hotels
============================================================
Places
9
0     Florianopolis (SC)
1          Salvador (BH)
2          Salvador (BH)
3          Salvador (BH)
4     Florianopolis (SC)
5             Natal (RN)
6           Aracaju (SE)
7            Recife (PE)
8         Sao Paulo (SP)
9          Salvador (BH)
10        Sao Paulo (SP)
11            Natal (RN)
12         Salvador (BH)
13     Campo Grande (MS)
14         Salvador (BH)
15            Natal (RN)
16         Salvador (BH)
17     Campo Grande (MS)
18        Sao Paulo (SP)
19    Florianopolis (SC)
Name: place, dtype: object

In [16]:
print("Age")
print(users["age"].describe())

print()

print("Flight Price")
print(flights["price"].describe())

print()

print("Flight Distance")
print(flights["distance"].describe())

print()

print("Flight Time")
print(flights["time"].describe())

print()

print("Hotel Days")
print(hotels["days"].describe())

print()

print("Hotel Price")
print(hotels["price"].describe())

print()

print("Hotel Total")
print(hotels["total"].describe())

Age
count    1340.000000
mean       42.742537
std        12.869779
min        21.000000
25%        32.000000
50%        42.000000
75%        54.000000
max        65.000000
Name: age, dtype: float64

Flight Price
count    271888.00000
mean        957.37503
std         362.31189
min         301.51000
25%         672.66000
50%         904.00000
75%        1222.24000
max        1754.17000
Name: price, dtype: float64

Flight Distance
count    271888.000000
mean        546.955535
std         208.851288
min         168.220000
25%         401.660000
50%         562.140000
75%         676.530000
max         937.770000
Name: distance, dtype: float64

Flight Time
count    271888.000000
mean          1.421147
std           0.542541
min           0.440000
25%           1.040000
50%           1.460000
75%           1.760000
max           2.440000
Name: time, dtype: float64

Hotel Days
count    40552.000000
mean         2.499679
std          1.119326
min          1.000000
25%          1.000000
50%          2.000000
75%          4.000000
max          4.000000
Name: days, dtype: float64

Hotel Price
count    40552.000000
mean       214.439554
std         76.742305
min         60.390000
25%        165.990000
50%        242.880000
75%        263.410000
max        313.020000
Name: price, dtype: float64

Hotel Total
count    40552.000000
mean       536.229513
std        319.331482
min         60.390000
25%        247.620000
50%        495.240000
75%        742.860000
max       1252.080000
Name: total, dtype: float64

In [21]:
import pandas as pd

hotels = pd.read_csv("../data/processed/hotels_processed.csv")

hotels[
    [
        "date",
        "days",
        "total",
        "stay_year",
        "stay_month",
        "stay_day",
        "stay_weekday",
        "stay_cost_per_day"
    ]
].head()

KeyError: "['stay_year', 'stay_month', 'stay_day', 'stay_weekday', 'stay_cost_per_day'] not in index"

In [28]:
import pandas as pd

users = pd.read_csv("../data/processed/users_processed.csv")

users[
    [
        "age",
        "age_group",
        "company",
        "company_frequency"
    ]
].head()

   age    age_group company  company_frequency
0   21  Young Adult    4You                453
1   37   Middle Age    4You                453
2   48   Middle Age    4You                453
3   23  Young Adult    4You                453
4   44   Middle Age    4You                453

In [30]:
import pandas as pd

final_df = pd.read_csv("../data/processed/final_dataset.csv")

print(final_df.shape)
print(final_df.columns.tolist())
final_df.head()

(271888, 34)
['code', 'company', 'name_x', 'gender', 'age', 'age_group', 'company_frequency', 'travelCode', 'userCode_x', 'from', 'to', 'flightType', 'price_x', 'time', 'distance', 'agency', 'date_x', 'travel_year', 'travel_month', 'travel_day', 'travel_weekday', 'is_weekend', 'userCode_y', 'name_y', 'place', 'days', 'price_y', 'total', 'date_y', 'stay_year', 'stay_month', 'stay_day', 'stay_weekday', 'stay_cost_per_day']

,code,company,name_x,gender,age,age_group,company_frequency,travelCode,userCode_x,from,to,flightType,price_x,time,distance,agency,date_x,travel_year,travel_month,travel_day,travel_weekday,is_weekend,userCode_y,name_y,place,days,price_y,total,date_y,stay_year,stay_month,stay_day,stay_weekday,stay_cost_per_day
0,0,4You,Roy Braun,male,21,Young Adult,453,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,2019-09-26,2019,9,26,Thursday,0,0.0,Hotel A,Florianopolis (SC),4.0,313.02,1252.08,2019-09-26,2019.0,9.0,26.0,Thursday,313.02
1,0,4You,Roy Braun,male,21,Young Adult,453,0,0,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,2019-09-30,2019,9,30,Monday,0,0.0,Hotel A,Florianopolis (SC),4.0,313.02,1252.08,2019-09-26,2019.0,9.0,26.0,Thursday,313.02
2,0,4You,Roy Braun,male,21,Young Adult,453,1,0,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,2019-10-03,2019,10,3,Thursday,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,4You,Roy Braun,male,21,Young Adult,453,1,0,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,2019-10-04,2019,10,4,Friday,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,4You,Roy Braun,male,21,Young Adult,453,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,2019-10-10,2019,10,10,Thursday,0,0.0,Hotel K,Salvador (BH),2.0,263.41,526.82,2019-10-10,2019.0,10.0,10.0,Thursday,263.41

In [34]:
hotels_processed=pd.read_csv("../data/processed/hotels_processed.csv")
hotels_processed.columns.tolist()

['travelCode',
 'userCode',
 'name',
 'place',
 'days',
 'price',
 'total',
 'date',
 'stay_year',
 'stay_month',
 'stay_day',
 'stay_weekday',
 'stay_cost_per_day']

In [35]:
hotels_processed.head()

,travelCode,userCode,name,place,days,price,total,date,stay_year,stay_month,stay_day,stay_weekday,stay_cost_per_day
0,0,0,Hotel A,Florianopolis (SC),4,313.02,1252.08,2019-09-26,2019,9,26,Thursday,313.02
1,2,0,Hotel K,Salvador (BH),2,263.41,526.82,2019-10-10,2019,10,10,Thursday,263.41
2,7,0,Hotel K,Salvador (BH),3,263.41,790.23,2019-11-14,2019,11,14,Thursday,263.41
3,11,0,Hotel K,Salvador (BH),4,263.41,1053.64,2019-12-12,2019,12,12,Thursday,263.41
4,13,0,Hotel A,Florianopolis (SC),1,313.02,313.02,2019-12-26,2019,12,26,Thursday,313.02